[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

solc = "0.8.25"
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

#[profile.optimizor]
#viaIR = true

optimize = true
optimize_runs = 20000